### PR TITLE
Improve documentation by providing correct argument example for `pem` option

### PR DESCRIPTION
**Pull request by miks**

### CODE REVIEW

**Comment by ebeigarts** [comment]
thnx

**Comment by Sacristan** [comment]
Totally agree! This has caused me headaches

**Comment by Sacristan** [comment]
@miks @ebeigarts 
```
gateway = ActiveMerchant::Billing::FirstDataGateway.new(
  pem:  File.read("1234567_keystore.pem")
  pem_password: "5x64jq8n234c"
)
```
------>>> (missing comma).If we want docs to be precise 
```
gateway = ActiveMerchant::Billing::FirstDataGateway.new(
  pem:  File.read("1234567_keystore.pem"),
  pem_password: "5x64jq8n234c"
)
```

**Comment by ebeigarts** [comment]
@Sacristan fixed :)

**Pull request merged**
